/**
 * `omp completions <bash|zsh|fish>` — print a shell completion script.
 *
 * The script is generated by `cli/completion-gen.ts` from a {@link CommandMeta}
 * list. The subcommand tree (names, short descriptions, hidden state, aliases)
 * is reflected off the live command registry so it never drifts from the actual
 * CLI surface. The top-level (`launch`) flags — and their value sources — are
 * declared here as typed owned metadata: Effect's `Command.Any` does not expose
 * its parsed flag metadata through a public API, and the OMP-specific dynamic
 * value sources (live model catalog, on-disk sessions, directories) that route
 * through the hidden `__complete` command are not expressible as Effect flag
 * metadata anyway. Enum sets sourced from shared constants (thinking efforts,
 * builtin tools) are imported so they stay in sync with the CLI.
 */
import { THINKING_EFFORTS } from "@oh-my-pi/pi-catalog/effort";
import { APP_NAME } from "@oh-my-pi/pi-utils";
import { Effect } from "effect";
import { Argument, Command } from "effect/unstable/cli";
import { buildSpec, type CommandMeta, type FlagMeta, generateCompletion } from "../cli/completion-gen";
import { commands } from "../cli-commands";

/** Registry name of the default command whose flags become top-level completions. */
const ROOT_COMMAND = "launch";
const SHELLS = ["bash", "zsh", "fish"] as const;

/**
 * The completable top-level (`launch`) flag surface. Value classification
 * (models/sessions/dir/list/enum) is applied by `completion-gen.ts` keyed on the
 * flag name; only enum `options`, `boolean`, `char`, and `multiple` are declared
 * here. `thinking` reuses the shared `THINKING_EFFORTS` catalog so the offered
 * levels never drift from the CLI.
 */
const LAUNCH_FLAGS: readonly FlagMeta[] = [
	{ name: "model", description: "Model to use (fuzzy match)" },
	{ name: "smol", description: "Smol/fast model for lightweight tasks" },
	{ name: "slow", description: "Slow/reasoning model for thorough analysis" },
	{ name: "plan", description: "Plan model for architectural planning" },
	{ name: "provider", description: "Provider to use (legacy; prefer --model)" },
	{ name: "api-key", description: "API key (defaults to env vars)" },
	{ name: "system-prompt", description: "System prompt (default: coding assistant prompt)" },
	{ name: "append-system-prompt", description: "Append text or file contents to the system prompt" },
	{ name: "allow-home", description: "Allow starting in ~ without auto-switching to a temp dir", boolean: true },
	{ name: "profile", description: "Use an isolated profile for auth, sessions, settings, and caches" },
	{ name: "alias", description: "Create a shell shortcut for the selected profile and exit" },
	{ name: "cwd", description: "Directory to start in (overrides the launch cwd)" },
	{ name: "workstream", description: "Classify the session with a workstream slug or adhoc" },
	{
		name: "mode",
		description: "Output mode: text (default), json, rpc, or rpc-ui",
		options: ["text", "json", "rpc", "acp", "rpc-ui"],
	},
	{ name: "tui-bundle-manifest", description: "Override the default rich terminal with a TUI bundle manifest" },
	{ name: "collab-host", description: "Host this runner-backed session for encrypted collaboration", boolean: true },
	{ name: "collab-relay", description: "Relay URL for runner-backed encrypted collaboration" },
	{ name: "config", description: "Load an extra config.yml-style overlay for this run (repeatable)", multiple: true },
	{ name: "print", char: "p", description: "Non-interactive mode: process prompt and exit", boolean: true },
	{ name: "continue", char: "c", description: "Continue previous session", boolean: true },
	{ name: "resume", char: "r", description: "Resume a session (by ID prefix, path, or picker if omitted)" },
	{ name: "session-dir", description: "Directory for session storage and lookup" },
	{ name: "no-session", description: "Don't save session (ephemeral)", boolean: true },
	{ name: "models", description: "Comma-separated model patterns for Ctrl+P cycling" },
	{ name: "no-tools", description: "Disable all built-in tools", boolean: true },
	{ name: "no-lsp", description: "Disable LSP tools, formatting, and diagnostics", boolean: true },
	{ name: "no-pty", description: "Disable PTY-based interactive bash execution", boolean: true },
	{ name: "tools", description: "Comma-separated list of tools to enable (default: all)" },
	{ name: "thinking", description: `Set thinking level: ${THINKING_EFFORTS.join(", ")}`, options: [...THINKING_EFFORTS] },
	{ name: "hide-thinking", description: "Hide thinking blocks in TUI output", boolean: true },
	{ name: "hook", description: "Load a hook/extension file (can be used multiple times)", multiple: true },
	{ name: "extension", char: "e", description: "Load an extension file (can be used multiple times)", multiple: true },
	{ name: "no-extensions", description: "Disable extension discovery (explicit -e paths still work)", boolean: true },
	{ name: "no-skills", description: "Disable skills discovery and loading", boolean: true },
	{ name: "skills", description: "Comma-separated glob patterns to filter skills (e.g., git-*,docker)" },
	{ name: "no-rules", description: "Disable rules discovery and loading", boolean: true },
	{ name: "export", description: "Export session file to HTML and exit" },
	{ name: "no-title", description: "Disable title auto-generation", boolean: true },
	{ name: "auto-approve", description: "Auto-approve all tool calls (skip approval prompts)", boolean: true },
	{
		name: "approval-mode",
		description: "Override tools.approvalMode for this session (always-ask|write|yolo)",
		options: ["always-ask", "write", "yolo"],
	},
];

/** Merge the Effect descriptor's single alias with the registry's alias list. */
function mergeAliases(alias: string | undefined, entryAliases: readonly string[] | undefined): string[] {
	const merged = new Set<string>();
	if (alias) merged.add(alias);
	for (const value of entryAliases ?? []) merged.add(value);
	return [...merged];
}

/**
 * Reflect the live command registry into completion metadata. Names and
 * registry aliases come from the entry table (stable routing identity); the
 * short description, hidden state, and descriptor alias are read off the loaded
 * `Command.Any`. Only the default command contributes completable flags.
 */
async function buildCommandMeta(): Promise<CommandMeta[]> {
	const loaded = await Promise.all(commands.map(async entry => ({ entry, command: await entry.load() })));
	return loaded.map(({ entry, command }) => ({
		name: entry.name,
		aliases: mergeAliases(command.alias, entry.aliases),
		description: command.shortDescription ?? command.description ?? "",
		hidden: command.hidden,
		flags: entry.name === ROOT_COMMAND ? LAUNCH_FLAGS : [],
		args: [],
	}));
}

export default Command.make(
	"completions",
	{
		shell: Argument.choice("shell", SHELLS).pipe(Argument.withDescription("Target shell")),
	},
	config =>
		Effect.promise(async () => {
			const meta = await buildCommandMeta();
			const spec = buildSpec(APP_NAME, meta, ROOT_COMMAND);
			await Bun.write(Bun.stdout, generateCompletion(config.shell, spec));
		}),
).pipe(
	Command.withDescription("Print a shell completion script (bash, zsh, or fish)"),
	Command.withExamples([
		{
			command: `eval "$(${APP_NAME} completions zsh)"`,
			description: "zsh — eval at startup, or write to a file in $fpath",
		},
		{ command: `eval "$(${APP_NAME} completions bash)"`, description: "bash" },
		{
			command: `${APP_NAME} completions fish > ~/.config/fish/completions/${APP_NAME}.fish`,
			description: "fish",
		},
	]),
);
