import type { BootstrapPayload, EvalElementDetail } from "../types"

const frames = [
  {
    index: 0,
    mimeType: "image/jpeg",
    path: "/repo/data/provider-evals/video-understanding/runs/run-a/artifacts/video/frame_001.jpg",
    sha256: "frame-001-sha",
    timestampSeconds: 0,
  },
  {
    index: 1,
    mimeType: "image/jpeg",
    path: "/repo/data/provider-evals/video-understanding/runs/run-a/artifacts/video/frame_002.jpg",
    sha256: "frame-002-sha",
    timestampSeconds: 12,
  },
]

export const fixtureBootstrap: BootstrapPayload = {
  server: {
    annotationsPath: "/repo/data/slotok-workbench/annotations.json",
    cwd: "/repo",
    evalRoot: "/repo/data/provider-evals/video-understanding",
    sqlitePath: "/repo/data/provider-evals/video-understanding/evals.sqlite",
    startedAt: "2026-06-08T09:00:00.000Z",
  },
  runs: [
    {
      run_id: "run_20260608090000_slotok",
      created_at: "2026-06-08T09:00:00.000Z",
      live: 1,
      providers_json: "[\"google\",\"kie\"]",
      videos_json: "[\"data/tiktok-catalogue/pleometric\"]",
      video_count: 1,
      limit_count: 1,
      max_frames: 2,
      frame_every_seconds: 12,
      max_output_tokens: 4096,
      prompt_hash: "prompt-hash",
      google_model: "gemini-2.5-flash",
      kie_model: "gemini-2.5-flash",
      out_dir: "/repo/data/provider-evals/video-understanding/runs/run-a",
      cache_dir: "/repo/data/provider-evals/video-understanding/cache",
      result_count: 2,
      completed_count: 1,
      cache_hit_count: 1,
      failed_count: 0,
      dry_run_count: 0,
      billed_cost_usd: 0.0018,
      avoided_cost_usd: 0.0063,
      avg_latency_ms: 9882,
    },
  ],
  elements: [
    {
      id: "element-kie",
      kind: "video_eval_result",
      title: "pleometric-green-blob.mp4 · kie",
      subtitle: "cache_hit / hit / gemini-2.5-flash",
      runId: "run_20260608090000_slotok",
      createdAt: "2026-06-08T09:00:00.100Z",
      videoId: "pleometric-green-blob_e133",
      videoPath: "/repo/data/tiktok-catalogue/pleometric/pleometric-green-blob.mp4",
      provider: "kie",
      model: "gemini-2.5-flash",
      status: "cache_hit",
      cacheStatus: "hit",
      stage: "video_understanding",
      version: "0e23eb53c7d6",
      metrics: {
        latencyMs: 0,
        estimatedCostUsd: 0,
        avoidedCostUsd: 0.0018,
        promptTokens: 4640,
        completionTokens: 1863,
        totalTokens: 6503,
        thoughtsTokens: null,
        rawCreditsConsumed: 0.36,
        finishReason: "stop",
        outputChars: 6467,
        parsedOk: true,
      },
      paths: {
        video: "/repo/data/tiktok-catalogue/pleometric/pleometric-green-blob.mp4",
        response: "/repo/data/provider-evals/video-understanding/cache/kie/0e23.json",
        parsed: "/repo/data/provider-evals/video-understanding/cache/kie/0e23.parsed.json",
        cache: "/repo/data/provider-evals/video-understanding/cache/kie/0e23.json",
      },
    },
    {
      id: "element-google-truncated",
      kind: "video_eval_result",
      title: "pleometric-green-blob.mp4 · google",
      subtitle: "completed / write / gemini-2.5-flash",
      runId: "run_20260608090000_slotok",
      createdAt: "2026-06-08T09:00:00.090Z",
      videoId: "pleometric-green-blob_e133",
      videoPath: "/repo/data/tiktok-catalogue/pleometric/pleometric-green-blob.mp4",
      provider: "google",
      model: "gemini-2.5-flash",
      status: "completed",
      cacheStatus: "write",
      stage: "video_understanding",
      version: "feea0106d49d",
      metrics: {
        latencyMs: 23968,
        estimatedCostUsd: 0.0062534,
        avoidedCostUsd: null,
        promptTokens: 2978,
        completionTokens: 2144,
        totalTokens: 7060,
        thoughtsTokens: 1938,
        rawCreditsConsumed: null,
        finishReason: "MAX_TOKENS",
        outputChars: 8923,
        parsedOk: false,
      },
      paths: {
        video: "/repo/data/tiktok-catalogue/pleometric/pleometric-green-blob.mp4",
        response: "/repo/data/provider-evals/video-understanding/cache/google/feea.json",
        parsed: "/repo/data/provider-evals/video-understanding/cache/google/feea.parsed.json",
        cache: "/repo/data/provider-evals/video-understanding/cache/google/feea.json",
      },
    },
  ],
  annotations: {},
  shortcuts: [
    { key: "j/k", description: "Move selection down/up" },
    { key: "g<letter>", description: "Switch Slotok view" },
  ],
}

export const fixtureDetail: EvalElementDetail = {
  ...fixtureBootstrap.elements[0]!,
  run: fixtureBootstrap.runs[0],
  result: {
    id: "element-kie",
    run_id: "run_20260608090000_slotok",
    created_at: "2026-06-08T09:00:00.100Z",
    video_id: "pleometric-green-blob_e133",
    video_path: "/repo/data/tiktok-catalogue/pleometric/pleometric-green-blob.mp4",
    duration_seconds: 60.09,
    width: 720,
    height: 1280,
    frame_count: 2,
    frames_json: JSON.stringify(frames),
    provider: "kie",
    model: "gemini-2.5-flash",
    status: "cache_hit",
    request_hash: "0e23eb53c7d6-request",
    cache_status: "hit",
    cache_path: "/repo/data/provider-evals/video-understanding/cache/kie/0e23.json",
    response_path: "/repo/data/provider-evals/video-understanding/cache/kie/0e23.json",
    parsed_path: "/repo/data/provider-evals/video-understanding/cache/kie/0e23.parsed.json",
    error: null,
    prompt_tokens: 4640,
    completion_tokens: 1863,
    total_tokens: 6503,
    thoughts_tokens: null,
    usage_json: "{}",
    latency_ms: 0,
    estimated_cost_usd: 0,
    avoided_cost_usd: 0.0018,
    raw_credits_consumed: 0.36,
    finish_reason: "stop",
    output_chars: 6467,
    parsed_ok: 1,
  },
  frames,
  parsed: {
    video_summary: "A surreal green blob cowboy lip-sync meme with industrial tunnel background and flashing captions.",
    format_family: "AI-LipSync-Meme",
    timeline: {
      segments: [
        { start_seconds: 0, end_seconds: 60.09, description: "Continuous talking-head blob performance." },
      ],
      transitions: [],
    },
    asset_generation_plan: [
      { asset_id: "character_base", layer: "subject", priority: "p0" },
      { asset_id: "caption_overlays", layer: "caption", priority: "p1" },
    ],
    provider_experiment_matrix: [
      { experiment_id: "lip_sync_test", layer_or_asset: "motion" },
    ],
  },
  rawPreview: "{\"choices\":[{\"message\":{\"content\":\"...\"}}]}",
  sectionAnnotations: {},
}

export const truncatedDetail: EvalElementDetail = {
  ...fixtureBootstrap.elements[1]!,
  result: {
    id: "element-google-truncated",
    run_id: "run_20260608090000_slotok",
    created_at: "2026-06-08T09:00:00.090Z",
    video_id: "pleometric-green-blob_e133",
    video_path: "/repo/data/tiktok-catalogue/pleometric/pleometric-green-blob.mp4",
    frame_count: 2,
    frames_json: JSON.stringify(frames),
    provider: "google",
    model: "gemini-2.5-flash",
    status: "completed",
    request_hash: "feea0106d49d-request",
    cache_status: "write",
    cache_path: "/repo/data/provider-evals/video-understanding/cache/google/feea.json",
  },
  frames,
  parsed: {
    rawText: "{\n  \"video_summary\": \"A truncated Google response that hit MAX_TOKENS before valid JSON finished.\"",
  },
  sectionAnnotations: {},
}
