import type { FormatTemplate, ModelSpec, PersonaSpec, SupercomputerMode } from "./types"

export const SUPERCOMPUTER_MODES: SupercomputerMode[] = [
  {
    id: "image_generation",
    label: "Image Generation",
    category: "generate",
    description: "Generate image prompt cards and routeable image jobs.",
    defaultModel: "image_auto",
  },
  {
    id: "video_generation",
    label: "Video Generation",
    category: "generate",
    description: "Generate video prompt cards and routeable video jobs.",
    defaultModel: "video_auto",
  },
  {
    id: "personal_clipper",
    label: "Personal Clipper",
    category: "editing",
    description: "Plan long-video to short-clip extraction with subtitles.",
    defaultModel: "clipper_local_plan",
  },
  {
    id: "ugc_tutorial",
    label: "UGC Tutorial",
    category: "marketing",
    description: "Step-by-step how-to ad with creator voiceover and product cutaways.",
    defaultModel: "marketing_studio_video",
  },
  {
    id: "animated_infographics",
    label: "Animated Infographics",
    category: "generate",
    description: "Data-story motion graphic plan with deterministic text overlays.",
    defaultModel: "motion_design_local_plan",
  },
  {
    id: "ai_influencer",
    label: "AI Influencer",
    category: "character",
    description: "Create a synthetic persona card for repeatable campaigns.",
    defaultModel: "soul_id_local_plan",
  },
  {
    id: "product_photoshoot",
    label: "Product Photoshoot",
    category: "marketing",
    description: "Plan product image generation and lifestyle shot prompts.",
    defaultModel: "marketing_studio_image",
  },
  {
    id: "ugc_content",
    label: "UGC Content",
    category: "marketing",
    description: "Creator-style content variants that do not depend on a real-person clone.",
    defaultModel: "arcads_ugc_pack",
  },
  {
    id: "virtual_try_on",
    label: "Virtual Try-On",
    category: "generate",
    description: "Plan apparel try-on image/video jobs with consent and product constraints.",
    defaultModel: "try_on_local_plan",
  },
  {
    id: "tv_commercial",
    label: "TV Commercial",
    category: "marketing",
    description: "Cinematic hero ad plan with product shots, voiceover, and CTA.",
    defaultModel: "marketing_studio_video",
  },
  {
    id: "unboxing_video",
    label: "Unboxing Video",
    category: "marketing",
    description: "POV unboxing shot list and prompt pack.",
    defaultModel: "arcads_ugc_pack",
  },
  {
    id: "amazon_listing_design",
    label: "Amazon Listing Design",
    category: "marketing",
    description: "Product card and listing image prompt cards.",
    defaultModel: "marketing_studio_image",
  },
  {
    id: "podcast_video",
    label: "Podcast Video",
    category: "marketing",
    description: "Authority-style podcast ad format with captions and product overlay.",
    defaultModel: "marketing_studio_video",
  },
  {
    id: "kinetic_typography",
    label: "Kinetic Typography",
    category: "editing",
    description: "Post-render text animation plan; text is never delegated to video models.",
    defaultModel: "motion_design_local_plan",
  },
  {
    id: "product_animation",
    label: "Product Animation",
    category: "generate",
    description: "Product motion prompt pack and timeline plan.",
    defaultModel: "video_auto",
  },
  {
    id: "virality_prediction",
    label: "Virality Prediction",
    category: "analysis",
    description: "Local heuristic report for hook, retention, clarity, and next tests.",
    defaultModel: "brain_activity",
  },
]

export const MODEL_CATALOG: ModelSpec[] = [
  {
    id: "arcads_ugc_pack",
    name: "Open UGC Pack Planner",
    family: "campaign",
    capability: "campaign.plan",
    providerMode: "local-plan",
    description: "Arcads-like product-to-UGC variant planner with scripts, B-roll prompts, captions, and JSON manifests.",
    estimatedCostUsd: 0,
    params: { variants: 3, formats: ["talking_head_product_cutaway", "show_app_creator", "unboxing_pov"] },
  },
  {
    id: "marketing_studio_video",
    name: "Open Marketing Studio Video Planner",
    family: "campaign",
    capability: "campaign.plan",
    providerMode: "local-plan",
    description: "Higgsfield-style marketing video command that plans assets across product ads, UGC, TV spot, and wild-card formats.",
    estimatedCostUsd: 0,
    params: { variants: 4, formats: ["ugc_tutorial", "product_review", "tv_commercial"] },
  },
  {
    id: "marketing_studio_image",
    name: "Open Marketing Studio Image Planner",
    family: "image",
    capability: "image.prompt_pack",
    providerMode: "local-plan",
    description: "Creates routeable product photo and listing-image prompt cards.",
    estimatedCostUsd: 0,
    params: { aspect_ratio: "1:1", count: 4 },
  },
  {
    id: "image_auto",
    name: "Image Auto Router",
    family: "image",
    capability: "image.generate",
    providerMode: "external-adapter",
    description: "Placeholder router for Gemini/OpenAI/Seedream/Flux adapters.",
    estimatedCostUsd: 0.04,
    params: { aspect_ratio: "1:1", resolution: "1024x1024" },
  },
  {
    id: "video_auto",
    name: "Video Auto Router",
    family: "video",
    capability: "video.generate",
    providerMode: "external-adapter",
    description: "Placeholder router for Jimeng/Kie/fal/Veo/Kling/Seedance adapters.",
    estimatedCostUsd: 0.5,
    params: { aspect_ratio: "9:16", duration: 5 },
  },
  {
    id: "brain_activity",
    name: "Open Virality Predictor",
    family: "analysis",
    capability: "video.analyze",
    providerMode: "local-plan",
    description: "Heuristic hook, retention-risk, caption, and product-clarity report.",
    estimatedCostUsd: 0,
    params: { rubric: ["hook", "retention", "caption_readability", "product_clarity"] },
  },
  {
    id: "soul_id_local_plan",
    name: "Synthetic Persona Card",
    family: "character",
    capability: "character.plan",
    providerMode: "local-plan",
    description: "Creates consent-safe synthetic persona specs for later image/voice generation.",
    estimatedCostUsd: 0,
    params: { referenceImages: "optional", consentStatus: "synthetic" },
  },
  {
    id: "clipper_local_plan",
    name: "Clipper Planner",
    family: "video",
    capability: "video.clip_plan",
    providerMode: "local-plan",
    description: "Plans long-video clip extraction, captions, and vertical crops.",
    estimatedCostUsd: 0,
    params: { clips: 3, aspect_ratio: "9:16" },
  },
  {
    id: "motion_design_local_plan",
    name: "Motion Design Planner",
    family: "video",
    capability: "render.timeline",
    providerMode: "local-plan",
    description: "Creates deterministic text/motion timeline JSON for Remotion/ffmpeg implementation.",
    estimatedCostUsd: 0,
    params: { fps: 30, width: 1080, height: 1920 },
  },
  {
    id: "try_on_local_plan",
    name: "Try-On Planner",
    family: "image",
    capability: "image.try_on_plan",
    providerMode: "local-plan",
    description: "Creates a guarded virtual try-on plan; does not submit model jobs.",
    estimatedCostUsd: 0,
    params: { requiresConsent: true },
  },
]

export const PERSONAS: PersonaSpec[] = [
  {
    id: "bedroom_creator",
    label: "Bedroom Creator",
    archetype: "peer creator",
    cameraStyle: "front-facing phone selfie, bedroom desk",
    energy: "fast, practical, lightly skeptical",
    trustSignal: "I tested this so you do not have to",
    voiceDirection: "conversational, dry, clipped",
    visualPrompt: "synthetic original UGC creator in a lived-in bedroom desk setup, phone selfie framing, ordinary lighting, realistic imperfections, no readable text",
    consentStatus: "synthetic",
  },
  {
    id: "founder_operator",
    label: "Founder Operator",
    archetype: "builder/founder",
    cameraStyle: "desk camera, laptop and product screen nearby",
    energy: "calm, direct, compressed",
    trustSignal: "operator explaining the workflow",
    voiceDirection: "plain-spoken founder demo",
    visualPrompt: "synthetic original founder-style creator at a desk, laptop glow, direct-to-camera product explanation, no logos, no readable text",
    consentStatus: "synthetic",
  },
  {
    id: "skeptical_reviewer",
    label: "Skeptical Reviewer",
    archetype: "reviewer",
    cameraStyle: "handheld selfie with quick cutaways",
    energy: "skeptical, then convinced",
    trustSignal: "critical before/after framing",
    voiceDirection: "slightly incredulous, fast ad read",
    visualPrompt: "synthetic original reviewer in casual room, handheld phone camera, natural face texture, imperfect framing, no readable text",
    consentStatus: "synthetic",
  },
  {
    id: "app_nerd",
    label: "App Nerd",
    archetype: "productivity/app enthusiast",
    cameraStyle: "screen-first app demo with face cutaway",
    energy: "precise, mildly obsessive",
    trustSignal: "shows the exact workflow",
    voiceDirection: "clear tutorial voice",
    visualPrompt: "synthetic original app reviewer with phone and laptop, clean desk, screen-demo energy, no readable text",
    consentStatus: "synthetic",
  },
  {
    id: "podcast_authority",
    label: "Podcast Authority",
    archetype: "authority commentator",
    cameraStyle: "podcast microphone, cropped studio angle",
    energy: "confident, explanatory",
    trustSignal: "expert-style opinion without regulated claims",
    voiceDirection: "measured podcast host",
    visualPrompt: "synthetic original podcast host in small studio, microphone, cinematic but realistic, no readable text",
    consentStatus: "synthetic",
  },
]

export const FORMAT_TEMPLATES: FormatTemplate[] = [
  {
    id: "talking_head_product_cutaway",
    label: "Talking Head + Product Cutaway",
    arcadsEquivalent: "Talking Actor + B-roll",
    higgsfieldEquivalent: "UGC Content",
    durationSec: 24,
    sceneRoles: ["hook", "problem", "creator explanation", "product cutaway", "proof", "cta"],
    captionStyle: "ugc_bold_bottom",
  },
  {
    id: "show_app_creator",
    label: "Show Your App Creator",
    arcadsEquivalent: "Show-your-app preset",
    higgsfieldEquivalent: "Marketing Studio product/app video",
    durationSec: 26,
    sceneRoles: ["hook", "phone mockup", "screen-record cutaway", "benefit", "cta"],
    captionStyle: "app_demo_clean",
  },
  {
    id: "unboxing_pov",
    label: "Unboxing POV",
    arcadsEquivalent: "Unboxing POV preset",
    higgsfieldEquivalent: "Unboxing Video",
    durationSec: 22,
    sceneRoles: ["curiosity hook", "box reveal", "product close-up", "first use", "cta"],
    captionStyle: "ugc_bold_bottom",
  },
  {
    id: "ugc_tutorial",
    label: "UGC Tutorial",
    arcadsEquivalent: "AI UGC workflow",
    higgsfieldEquivalent: "UGC Tutorial",
    durationSec: 30,
    sceneRoles: ["pain hook", "step one", "step two", "result", "cta"],
    captionStyle: "tutorial_steps",
  },
  {
    id: "product_review",
    label: "Skeptical Product Review",
    arcadsEquivalent: "Hook repurposer / product showcase",
    higgsfieldEquivalent: "UGC Try-On / Product Review",
    durationSec: 25,
    sceneRoles: ["skeptical hook", "test setup", "result", "verdict", "cta"],
    captionStyle: "ugc_bold_bottom",
  },
  {
    id: "tv_commercial",
    label: "Mini TV Commercial",
    arcadsEquivalent: "Cinematic video + product showcase",
    higgsfieldEquivalent: "TV Commercial",
    durationSec: 18,
    sceneRoles: ["hero shot", "problem line", "product beauty shot", "brand promise", "cta"],
    captionStyle: "cinematic_minimal",
  },
  {
    id: "wild_card",
    label: "Wild Card Brainrot Overlay",
    arcadsEquivalent: "Workflow remix / B-roll idea generator",
    higgsfieldEquivalent: "Wild Card marketing format",
    durationSec: 20,
    sceneRoles: ["absurd hook", "visual ritual", "product slot", "caption gag", "cta"],
    captionStyle: "brainrot_dense",
  },
]
