Match User remote-auth-sudo-ingest
    AuthenticationMethods publickey
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AuthorizedKeysFile /etc/remote-auth-broker/ssh/remote-auth-sudo-ingest.authorized_keys
    ForceCommand /usr/libexec/remote-auth-broker/current/bin/remote-auth-broker-sudo-ingest
    DisableForwarding yes
    AllowAgentForwarding no
    AllowTcpForwarding no
    AllowStreamLocalForwarding no
    GatewayPorts no
    PermitOpen none
    PermitListen none
    PermitTTY no
    PermitTunnel no
    PermitUserEnvironment no
    PermitUserRC no
    X11Forwarding no
    MaxSessions 1

Match all
