Match User remote-auth-gdm-ingest
    AuthenticationMethods publickey
    PubkeyAuthentication yes
    AuthorizedKeysFile /etc/remote-auth-broker/gdm-ingest.authorized_keys
    DisableForwarding yes
    ForceCommand /usr/libexec/remote-auth-broker/current/bin/remote-auth-gdm-ingest
    KbdInteractiveAuthentication no
    PasswordAuthentication no
    PermitTTY no
    PermitUserRC no
    X11Forwarding no
Match all
