# Type Path                                         Mode User Group                  Age Argument
d /run/remote-auth-broker                           0755 root root                   -   -
d /run/remote-auth-broker/gdm                       0750 root remote-auth-gdm-ingest -   -
d /run/remote-auth-broker/rollback                  0700 root root                   -   -
d /var/lib/remote-auth-broker                       0700 root root                   -   -
d /var/lib/remote-auth-broker/gdm                   0700 root root                   -   -
d /var/lib/remote-auth-broker/pam-backups           0700 root root                   -   -
d /var/lib/remote-auth-broker/releases              0755 root root                   -   -
