#!/usr/bin/env bun
import * as fs from "node:fs/promises"
import * as path from "node:path"

interface DomainEntry {
  name: string
  port: number
  host?: string
  enabled?: boolean
  description?: string
  command?: string
}

interface DevDomainRegistry {
  listen?: string
  domains?: DomainEntry[]
}

const DEFAULT_REGISTRY = ".dev-domains.json"
const DEFAULT_OUTPUT = "infra/dev-proxy/Caddyfile"
const NAME_RE = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/

interface CliOptions {
  command: "render" | "run" | "reload" | "validate" | "help"
  registryPath: string
  outputPath: string
  listen?: string
}

function parseArgs(argv: string[]): CliOptions {
  const options: CliOptions = {
    command: "run",
    registryPath: DEFAULT_REGISTRY,
    outputPath: DEFAULT_OUTPUT,
  }
  const [first, ...rest] = argv
  let args = argv
  if (first && !first.startsWith("--")) {
    if (!["render", "run", "reload", "validate", "help"].includes(first)) {
      throw new Error(`Unknown dev-proxy command: ${first}`)
    }
    options.command = first as CliOptions["command"]
    args = rest
  }
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i]
    if (arg === "--registry") options.registryPath = requiredValue(args, ++i, arg)
    else if (arg === "--output") options.outputPath = requiredValue(args, ++i, arg)
    else if (arg === "--listen") options.listen = requiredValue(args, ++i, arg)
    else if (arg === "--help" || arg === "-h") options.command = "help"
    else throw new Error(`Unknown dev-proxy option: ${arg}`)
  }
  return options
}

function requiredValue(args: string[], index: number, flag: string): string {
  const value = args[index]
  if (!value || value.startsWith("--")) throw new Error(`${flag} requires a value`)
  return value
}

function usage(): string {
  return `Usage: bun scripts/dev-proxy.ts [run|render|reload|validate] [--registry .dev-domains.json] [--output infra/dev-proxy/Caddyfile] [--listen :80]

Commands:
  run       Render the Caddyfile and run caddy in the foreground.
  render    Render the Caddyfile only.
  reload    Render the Caddyfile and ask a running caddy instance to reload it.
  validate  Render and validate the Caddyfile with caddy validate.

Default URLs use http://<name>.localhost with a listener on :80. Use --listen :18080 for unprivileged tests.`
}

async function readRegistry(registryPath: string): Promise<DevDomainRegistry> {
  const text = await fs.readFile(registryPath, "utf8")
  const parsed = JSON.parse(text) as unknown
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("registry must be a JSON object")
  return parsed as DevDomainRegistry
}

function enabledDomains(registry: DevDomainRegistry): DomainEntry[] {
  const domains = registry.domains
  if (!Array.isArray(domains)) throw new Error("registry.domains must be an array")
  const seen = new Set<string>()
  return domains.filter((entry) => {
    if (entry.enabled === false) return false
    validateEntry(entry)
    const key = entry.name
    if (seen.has(key)) throw new Error(`duplicate dev domain: ${key}`)
    seen.add(key)
    return true
  })
}

function validateEntry(entry: DomainEntry): void {
  if (!NAME_RE.test(entry.name)) throw new Error(`invalid dev domain name: ${entry.name}`)
  if (!Number.isInteger(entry.port) || entry.port < 1 || entry.port > 65535) {
    throw new Error(`invalid port for ${entry.name}: ${entry.port}`)
  }
  if (entry.host !== undefined && !/^[a-zA-Z0-9.:-]+$/.test(entry.host)) {
    throw new Error(`invalid upstream host for ${entry.name}: ${entry.host}`)
  }
}

function validateListen(value: string): string {
  if (!/^(?::\d{1,5}|127\.0\.0\.1:\d{1,5}|localhost:\d{1,5})$/.test(value)) {
    throw new Error(`invalid listen address: ${value}`)
  }
  const port = Number(value.slice(value.lastIndexOf(":") + 1))
  if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error(`invalid listen port: ${value}`)
  return value
}

function renderCaddyfile(registry: DevDomainRegistry, listenOverride?: string): string {
  const listen = validateListen(listenOverride ?? registry.listen ?? ":80")
  const lines = [
    "# Generated by scripts/dev-proxy.ts from .dev-domains.json; edit the registry, not this file.",
    "{",
    "\tauto_https off",
    "}",
    "",
    `${listen} {`,
    "\tbind 127.0.0.1 ::1",
  ]
  for (const entry of enabledDomains(registry)) {
    const upstreamHost = entry.host ?? "127.0.0.1"
    lines.push(
      `\t@${entry.name} host ${entry.name}.localhost`,
      `\thandle @${entry.name} {`,
      `\t\treverse_proxy ${upstreamHost}:${entry.port}`,
      "\t}",
      "",
    )
  }
  lines.push(
    "\thandle {",
    "\t\trespond \"Unknown dev domain\" 404",
    "\t}",
    "}",
    "",
  )
  return lines.join("\n")
}

async function writeCaddyfile(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true })
  await fs.writeFile(filePath, content)
}

async function runCaddy(args: string[]): Promise<void> {
  const proc = Bun.spawn(["caddy", ...args], { stdout: "inherit", stderr: "inherit", stdin: "inherit" })
  const code = await proc.exited
  if (code !== 0) throw new Error(`caddy ${args[0]} exited with ${code}`)
}

async function main(): Promise<void> {
  const options = parseArgs(Bun.argv.slice(2))
  if (options.command === "help") {
    console.log(usage())
    return
  }
  const registry = await readRegistry(options.registryPath)
  const caddyfile = renderCaddyfile(registry, options.listen)
  await writeCaddyfile(options.outputPath, caddyfile)
  if (options.command === "render") {
    console.log(`Rendered ${options.outputPath}`)
    return
  }
  if (options.command === "validate") {
    await runCaddy(["validate", "--config", options.outputPath, "--adapter", "caddyfile"])
    return
  }
  if (options.command === "reload") {
    await runCaddy(["reload", "--config", options.outputPath, "--adapter", "caddyfile"])
    return
  }
  await runCaddy(["run", "--config", options.outputPath, "--adapter", "caddyfile"])
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exitCode = 1
})
