import { Schema } from "effect"

export const SourceCategory = Schema.Union([
  Schema.Literal("commercial-residential"),
  Schema.Literal("static-residential"),
  Schema.Literal("distributed-browser-network"),
  Schema.Literal("consumer-residential-vpn"),
  Schema.Literal("vpn-privacy"),
  Schema.Literal("p2p-bandwidth-sharing"),
  Schema.Literal("self-operated"),
  Schema.Literal("grey-market-resale"),
  Schema.Literal("bulletproof-hosting"),
  Schema.Literal("compromised-botnet"),
  Schema.Literal("public-free-list"),
])
export type SourceCategory = typeof SourceCategory.Type

export const RiskTier = Schema.Union([
  Schema.Literal("low"),
  Schema.Literal("moderate"),
  Schema.Literal("high"),
  Schema.Literal("critical"),
])
export type RiskTier = typeof RiskTier.Type

export const CostTier = Schema.Union([
  Schema.Literal("free"),
  Schema.Literal("cheap"),
  Schema.Literal("moderate"),
  Schema.Literal("expensive"),
])
export type CostTier = typeof CostTier.Type

export const PricingModel = Schema.Union([
  Schema.Literal("per-gb"),
  Schema.Literal("per-ip-month"),
  Schema.Literal("flat-monthly"),
  Schema.Literal("free"),
])
export type PricingModel = typeof PricingModel.Type

export const IpType = Schema.Union([
  Schema.Literal("residential"),
  Schema.Literal("mobile"),
  Schema.Literal("datacenter"),
  Schema.Literal("vpn"),
  Schema.Literal("mixed"),
])
export type IpType = typeof IpType.Type

export const ProxyProvider = Schema.Struct({
  id: Schema.String,
  name: Schema.String,
  category: SourceCategory,
  ipType: IpType,
  riskTier: RiskTier,
  costTier: CostTier,
  pricingModel: PricingModel,
  approxPriceUsdPerGb: Schema.Union([Schema.Number, Schema.Literal("n/a")]),
  freeTier: Schema.Boolean,
  usEgress: Schema.Boolean,
  auEgress: Schema.Boolean,
  notes: Schema.String,
})
export type ProxyProvider = typeof ProxyProvider.Type

export const defaultProviderMatrix: ReadonlyArray<ProxyProvider> = [
  {
    id: "dataimpulse",
    name: "DataImpulse",
    category: "commercial-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 1.0,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "PAYG, often cited as the value floor for residential traffic.",
  },
  {
    id: "thordata",
    name: "Thordata",
    category: "commercial-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 0.65,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Self-serve with city/ASN targeting.",
  },
  {
    id: "proxyrack",
    name: "Proxyrack",
    category: "commercial-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 1.0,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Tiered pricing by threads/volume.",
  },
  {
    id: "iproyal",
    name: "IPRoyal",
    category: "commercial-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "moderate",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 1.75,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Non-expiring bandwidth.",
  },
  {
    id: "oxylabs",
    name: "Oxylabs",
    category: "commercial-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "expensive",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 5.0,
    freeTier: true,
    usEgress: true,
    auEgress: true,
    notes: "Enterprise grade; free trial available.",
  },
  {
    id: "brightdata",
    name: "Bright Data",
    category: "commercial-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "expensive",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 5.0,
    freeTier: true,
    usEgress: true,
    auEgress: true,
    notes: "Enterprise grade with SDK-based P2P panel.",
  },
  {
    id: "evomi-core",
    name: "Evomi Core Residential",
    category: "commercial-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 0.49,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Rotating residential pool; among the cheapest per-GB residential proxies.",
  },
  {
    id: "evomi-static",
    name: "Evomi Static Residential (ISP)",
    category: "static-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "per-ip-month",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Static residential IPs at ~$1.00/IP/mo with unlimited bandwidth; cheapest flat-rate option.",
  },
  {
    id: "webshare",
    name: "Webshare",
    category: "commercial-residential",
    ipType: "datacenter",
    riskTier: "low",
    costTier: "free",
    pricingModel: "free",
    approxPriceUsdPerGb: "n/a",
    freeTier: true,
    usEgress: true,
    auEgress: true,
    notes: "Free tier is 10 dedicated datacenter proxies + 1 GB/mo, not residential.",
  },
  {
    id: "browsercash",
    name: "Browser Cash",
    category: "distributed-browser-network",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "per-ip-month",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Distributed browser nodes via user extension; residential IPs from opted-in home connections.",
  },
  {
    id: "driverdev",
    name: "Driver.dev",
    category: "distributed-browser-network",
    ipType: "residential",
    riskTier: "low",
    costTier: "moderate",
    pricingModel: "flat-monthly",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Hosted real-hardware browser PoPs with ISP-contract residential IPs; CDP/Playwright/Puppeteer API.",
  },
  {
    id: "iproyal-isp",
    name: "IPRoyal ISP proxies",
    category: "static-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "per-ip-month",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Static residential IPs from ISP ASNs; ~$2.40–$5.40/IP/mo with unlimited bandwidth.",
  },
  {
    id: "webshare-isp",
    name: "Webshare ISP proxies",
    category: "static-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "per-ip-month",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Static ISP proxies starting around $3/IP/mo; often with unlimited bandwidth.",
  },
  {
    id: "brightdata-isp",
    name: "Bright Data ISP proxies",
    category: "static-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "moderate",
    pricingModel: "per-ip-month",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Static residential IPs from ISPs; priced per IP/month with high fair-use limits.",
  },
  {
    id: "oxylabs-isp",
    name: "Oxylabs Static Residential Proxies",
    category: "static-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "moderate",
    pricingModel: "per-ip-month",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "ISP-sourced static IPs; per-IP monthly pricing.",
  },
  {
    id: "us-isp-business-line",
    name: "US ISP business line with static IP",
    category: "static-residential",
    ipType: "residential",
    riskTier: "low",
    costTier: "expensive",
    pricingModel: "flat-monthly",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: false,
    notes: "True residential/business connection with static IP; $50–$200/mo depending on ISP.",
  },
  {
    id: "mullvad",
    name: "Mullvad VPN",
    category: "vpn-privacy",
    ipType: "vpn",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "flat-monthly",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: false,
    notes: "Flat monthly fee; US exits but datacenter ASNs, often blocked by targets.",
  },
  {
    id: "windscribe",
    name: "Windscribe",
    category: "vpn-privacy",
    ipType: "vpn",
    riskTier: "low",
    costTier: "free",
    pricingModel: "free",
    approxPriceUsdPerGb: "n/a",
    freeTier: true,
    usEgress: true,
    auEgress: false,
    notes: "Free 10 GB/mo with US exits; Build-a-Plan for cheap paid tier.",
  },
  {
    id: "protonvpn",
    name: "Proton VPN",
    category: "vpn-privacy",
    ipType: "vpn",
    riskTier: "low",
    costTier: "free",
    pricingModel: "free",
    approxPriceUsdPerGb: "n/a",
    freeTier: true,
    usEgress: true,
    auEgress: false,
    notes: "Free tier includes US servers; slower than paid.",
  },
  {
    id: "cloudflare-warp",
    name: "Cloudflare WARP+",
    category: "vpn-privacy",
    ipType: "vpn",
    riskTier: "low",
    costTier: "free",
    pricingModel: "free",
    approxPriceUsdPerGb: "n/a",
    freeTier: true,
    usEgress: true,
    auEgress: true,
    notes: "Sometimes egresses from US Cloudflare PoPs; not residential.",
  },
  {
    id: "windscribe-residential",
    name: "Windscribe + Residential IP add-on",
    category: "consumer-residential-vpn",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "per-ip-month",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: false,
    notes: "VPN base plan plus static residential IP add-on (~$2/IP/mo); polished apps, unlimited bandwidth.",
  },
  {
    id: "hola-vpn",
    name: "Hola VPN",
    category: "consumer-residential-vpn",
    ipType: "residential",
    riskTier: "moderate",
    costTier: "free",
    pricingModel: "free",
    approxPriceUsdPerGb: "n/a",
    freeTier: true,
    usEgress: true,
    auEgress: true,
    notes: "P2P residential VPN; free tier makes your device an exit node for others. Privacy concerns.",
  },
  {
    id: "self-home-node",
    name: "Self-operated home node",
    category: "self-operated",
    ipType: "residential",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "flat-monthly",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: false,
    notes: "Raspberry Pi or mini-PC at a US residence with documented consent.",
  },
  {
    id: "self-mobile-node",
    name: "Self-operated mobile node",
    category: "self-operated",
    ipType: "mobile",
    riskTier: "low",
    costTier: "cheap",
    pricingModel: "flat-monthly",
    approxPriceUsdPerGb: "n/a",
    freeTier: false,
    usEgress: true,
    auEgress: false,
    notes: "US phone/SIM with USB tether + WireGuard backhaul.",
  },
  {
    id: "packetstream",
    name: "PacketStream",
    category: "p2p-bandwidth-sharing",
    ipType: "residential",
    riskTier: "moderate",
    costTier: "cheap",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 1.5,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "P2P bandwidth marketplace; consent is often low-information.",
  },
  {
    id: "honeygain",
    name: "Honeygain",
    category: "p2p-bandwidth-sharing",
    ipType: "residential",
    riskTier: "moderate",
    costTier: "cheap",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 1.5,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Bandwidth-sharing app; more suited to passive income than proxy research.",
  },
  {
    id: "brightdata-sdk",
    name: "Bright Data SDK (P2P panel)",
    category: "p2p-bandwidth-sharing",
    ipType: "residential",
    riskTier: "moderate",
    costTier: "moderate",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 3.0,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "App-embedded SDK where end users opt in via ToS.",
  },
  {
    id: "resold-isp-account",
    name: "Resold ISP/customer account",
    category: "grey-market-resale",
    ipType: "residential",
    riskTier: "high",
    costTier: "cheap",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 1.0,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Likely violates ISP ToS; identity-fraud risk if accounts are stolen.",
  },
  {
    id: "sim-farm",
    name: "US SIM farm / mobile proxy",
    category: "grey-market-resale",
    ipType: "mobile",
    riskTier: "high",
    costTier: "moderate",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 2.5,
    freeTier: false,
    usEgress: true,
    auEgress: false,
    notes: "Legal only if you own the SIMs and contracts; high carrier-ToS risk otherwise.",
  },
  {
    id: "bulletproof-hosting",
    name: "Bulletproof / offshore host",
    category: "bulletproof-hosting",
    ipType: "mixed",
    riskTier: "critical",
    costTier: "cheap",
    pricingModel: "per-gb",
    approxPriceUsdPerGb: 1.0,
    freeTier: false,
    usEgress: true,
    auEgress: true,
    notes: "Often mixes datacenter and compromised residential IPs; high fraud association.",
  },
  {
    id: "compromised-botnet",
    name: "Compromised IoT / botnet proxy",
    category: "compromised-botnet",
    ipType: "residential",
    riskTier: "critical",
    costTier: "free",
    pricingModel: "free",
    approxPriceUsdPerGb: 0,
    freeTier: true,
    usEgress: true,
    auEgress: true,
    notes: "Criminal under AU/US computer-misuse law; do not use.",
  },
  {
    id: "public-free-list",
    name: "Public free proxy list",
    category: "public-free-list",
    ipType: "mixed",
    riskTier: "critical",
    costTier: "free",
    pricingModel: "free",
    approxPriceUsdPerGb: 0,
    freeTier: true,
    usEgress: true,
    auEgress: true,
    notes: "Open relays, often misconfigured or malware; traffic interception risk.",
  },
]

export function providersByCategory(
  category: SourceCategory,
): ReadonlyArray<ProxyProvider> {
  return defaultProviderMatrix.filter((p) => p.category === category)
}

export function providersByRisk(
  riskTier: RiskTier,
): ReadonlyArray<ProxyProvider> {
  return defaultProviderMatrix.filter((p) => p.riskTier === riskTier)
}

export function providersByUseCase(filters: {
  readonly usEgress?: boolean
  readonly freeTier?: boolean
  readonly maxRiskTier?: RiskTier
  readonly maxCostTier?: CostTier
}): ReadonlyArray<ProxyProvider> {
  const riskOrder: ReadonlyArray<RiskTier> = ["low", "moderate", "high", "critical"]
  const costOrder: ReadonlyArray<CostTier> = ["free", "cheap", "moderate", "expensive"]

  const maxRiskIndex = filters.maxRiskTier ? riskOrder.indexOf(filters.maxRiskTier) : Infinity
  const maxCostIndex = filters.maxCostTier ? costOrder.indexOf(filters.maxCostTier) : Infinity

  return defaultProviderMatrix.filter((p) => {
    if (filters.usEgress !== undefined && p.usEgress !== filters.usEgress) return false
    if (filters.freeTier !== undefined && p.freeTier !== filters.freeTier) return false
    if (Number.isFinite(maxRiskIndex) && riskOrder.indexOf(p.riskTier) > maxRiskIndex) return false
    if (Number.isFinite(maxCostIndex) && costOrder.indexOf(p.costTier) > maxCostIndex) return false
    return true
  })
}

export function lowestRiskUsEgressProviders(): ReadonlyArray<ProxyProvider> {
  return providersByUseCase({ usEgress: true, maxRiskTier: "low" })
}
